config/routes.rb
Rails.application.routes.draw do
  resources :levels do
    resources :scores
  end

  root to: 'levels#index'

  devise_for :users

  get 'levels/:id/play' => 'levels#play', as: :play
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/level.rb
class Level < ApplicationRecord
  belongs_to :user

  validates :name,    presence: true, length: { maximum: 100 }
  validates :code,    presence: true
  validates :user_id, presence: true

  has_many :scores
end

app/models/score.rb
class Score < ApplicationRecord
  belongs_to :level
  belongs_to :user

  default_scope -> { order(value: :desc) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :levels
  has_many :scores
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
  skip_before_action :verify_authenticity_token
end

app/controllers/levels_controller.rb
class LevelsController < ApplicationController
  before_action :set_level, only: [:show, :play]
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /levels
  def index
    @levels = Level.all
  end

  # GET /levels/1
  def show
    respond_to do |format|
      format.html { render :show }
      format.js   { render plain: @level.code }
    end
  end

  # GET /levels/1/play
  def play
  end

  # GET /levels/new
  def new
    @level = Level.new
  end

  # GET /levels/1/edit
  def edit
  end

  # POST /levels
  def create
    @level = current_user.levels.new(level_params)

    if @level.save
      redirect_to @level, notice: 'Level was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /levels/
  def update
    if @level.update(level_params)
      redirect_to @level, notice: 'Level was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /levels/1
  def destroy
    @level.destroy
    redirect_to levels_url, notice: 'Level was successfully destroyed.'
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_level
    @level = Level.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def level_params
    params.require(:level).permit(:name, :code, :user_id)
  end

  def correct_user
    @level = current_user.levels.find(params[:id])
    redirect_to root_url if @level.nil?
  end
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  before_action :set_scores
  before_action :set_score, only: [:show, :edit, :update, :destroy]

  # GET levels/1/scores
  def index
    @scores = @level.scores
  end

  # GET levels/1/scores/1
  def show
  end

  # GET levels/1/scores/new
  def new
    @score = @level.scores.build
  end

  # GET levels/1/scores/1/edit
  def edit
  end

  # POST levels/1/scores
  def create
    @score = @level.scores.build(score_params)

    if @score.save
      respond_to do |format|
        format.json { render json: @score }
        format.html { redirect_to([@score.level, @score], notice: 'Score was successfully created.') }
      end
    else
      render action: 'new'
    end
  end

  # PUT levels/1/scores/1
  def update
    if @score.update_attributes(score_params)
      respond_to do |format|
        format.json { render json: @score }
        format.html { redirect_to([@score.level, @score], notice: 'Score was successfully updated.') }
      end
    else
      render action: 'edit'
    end
  end

  # DELETE levels/1/scores/1
  def destroy
    @score.destroy

    redirect_to level_scores_url(@level)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scores
      @level = Level.find(params[:level_id])
    end

    def set_score
      @score = @level.scores.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def score_params
      params.require(:score).permit(:value, :level_id, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = 'GameServer'
    if page_title.empty?
      base_title
    else
      page_title + ' | ' + base_title
    end
  end
end

app/helpers/levels_helper.rb
module LevelsHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/views/layouts/_menu.html.erb
<nav>
  <div class="nav-wrapper">
    <a href="/levels" class="brand-logo">Game Server</a>
    <ul id="nav-mobile" class="right hide-on-med-and-down">
      <% if user_signed_in? %>
        <li>
          <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
        </li>
      <% else %>
        <li>
          <%= link_to('Login', new_user_session_path)  %>
        </li>
        <li>
          <%= link_to('Register', new_user_registration_path)  %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/_rails_defaults.html.erb
<%= csrf_meta_tags %>

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>

    <%= render 'layouts/rails_defaults' %>
  </head>

  <body>
    <div class="row">
      <%= render 'layouts/menu' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/levels/_form.html.erb
<div class="col s6 offset-s3 center">
  <%= form_with(model: level, local: true) do |form| %>
    <div class="input-field">
      <i class="material-icons prefix">info</i>
      <%= form.label :name %>
      <%= form.text_field :name, id: :level_name %>
    </div>

    <div class="input-field">
      <i class="material-icons prefix">code</i>
      <%= form.label :code %>
      <%= form.text_area :code, id: :level_code, class: 'materialize-textarea' %>
    </div>

    <div class="input-field">
      <%= form.submit "#{button_title} level", class: 'waves-effect waves-light btn' %>
    </div>
  <% end %>
</div>

app/views/levels/_level_heading.html.erb
<div class="center-align">
  <h4>Level <span class="grey-text">"<%= @level.name %>"</span></h4>
  <h6>by <span class="grey-text"><%= @level.user.email %></span></h6>

  <div class="row"></div>
</div>

app/views/levels/edit.html.erb
<% provide(:title, "Editing level \"#{@level.name}\"") %>

<h2 class="center">Editing level <span class="grey-text">"<%= @level.name %>"</span></h2>

<%= render 'form', level: @level, button_title: 'Update' %>

app/views/levels/index.html.erb
<% provide(:title, 'Levels') %>

<div class="col s6 offset-s3">
  <% if @levels.empty? %>
    <div class="center-align">
      <h2>There are no available levels ... :(</h2>
      <h3>Be the first to <%= link_to 'add one', new_level_path %></h3>
    </div>
  <% else %>
    <ul class="collection with-header">
      <li class="collection-header center">
        <h4>Levels</h4>
      </li>
      <% @levels.each do |level| %>
        <li class="collection-item avatar">
          <a href="<%= level_path(level) %>" class="title"><strong>Level #<%= level.id %></strong></a>
          <p><span class="grey-text">Name:</span> "<%= level.name %>"</p>
          <p><span class="grey-text">Author:</span> <%= level.user.email %></p>
          <a href="<%= play_path(level) %>" class="secondary-content"><i class="material-icons medium">play_circle_filled</i></a>
        <li>
      <% end %>
    </ul>
     <div class="fixed-action-btn">
      <a href="<%= new_level_path %>"class="btn waves-effect btn-floating btn-large">
        <i class="large material-icons">add</i>
      </a>
    </div>
  <% end %>
</div>

app/views/levels/new.html.erb
<% provide(:title, 'Creating a new level') %>

<h2 class="center">Creating a new level</h2>

<%= render 'form', level: @level, button_title: 'Create' %>

app/views/levels/play.html.erb
<% provide(:title, "Playing level \"#{@level.name}\"") %>

<div class="col s10 offset-s1">
  <%= render 'level_heading' %>

  <div class="col s8 offset-s2">
    <div class="row" id="stats-bar">
      <div class="col s6 center">Score: <span id="score">0</span></div>
      <div class="col s6 center">Lives: <san id="lives">3</span></div>
    </div>
    <canvas id="tutorial" width="1000" height="600"></canvas>
  </div>

  <%= javascript_include_tag level_path(@level, format: :js) %>
</div>

app/views/levels/show.html.erb
<% provide(:title, "Level \"#{@level.name}\"") %>

<div class="col s8 offset-s2">
  <%= render 'level_heading' %>

  <% if current_user == @level.user %>
    <div class="center">
      <%= link_to 'Edit', edit_level_path(@level), class: 'waves-effect waves-light btn' %>
      <%= link_to 'Delete', @level, id: 'delete-level-button', class: 'waves-effect waves-light btn', method: :delete, data: {confirm: "Are you sure?"} %>
    </div>
  <% end %>

  <h5>Source code:</h5>
  <blockquote class="level-content">
    <pre><code class="language-markup"><%= @level.code %></code></pre>
  </blockquote>

  <div class="center-align">
    <a href="<%= play_path(@level) %>" class="waves-effect waves-light btn-large"><i class="material-icons right">play_circle_outline</i>Play</a>
  </div>

  <br>

  <div class="center-align">
    <a href="<%= level_scores_path(@level) %>" class="waves-effect waves-light btn-large"><i class="material-icons right">info_outline</i>Leaderboard</a>
  </div>
</div>

app/views/scores/_form.html.erb
<%= form_for([@score.level, @score]) do |f| %>
  <% if @score.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@score.errors.count, "error") %> prohibited this score from being saved:</h2>

      <ul>
      <% @score.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :value %><br />
    <%= f.number_field :value %>
  </div>
  <div class="field">
    <%= f.label :level %><br />
    <%= f.text_field :level %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/scores/edit.html.erb
<h1>Editing score</h1>

<%= render 'form' %>

<%= link_to 'Show', [@score.level, @score] %> |
<%= link_to 'Back', level_scores_path(@score.level) %>

app/views/scores/index.html.erb
<div class="col s10 offset-s1 center">

  <% if @scores.empty? %>
    <h2>No scores available</h2>
  <% else %>
    <h1>Leaderboard for "<%= @scores.first.level.name %>"</h1>

    <table class="centered bordered highlight">
      <thead>
        <tr>
          <th>Score</th>
          <th>User</th>
        </tr>
      </thead>
      <tbody>
        <% @scores.each do |score| %>
          <tr>
            <td><%= score.value %></td>
            <td><%= score.user.email %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  
    <br />
  <% end %>

</div>

app/views/scores/new.html.erb
<h1>New score</h1>

<%= render 'form' %>

<%= link_to 'Back', level_scores_path(@score.level) %>

app/views/scores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Value:</b>
  <%= @score.value %>
</p>

<p>
  <b>Level:</b>
  <%= @score.level %>
</p>

<p>
  <b>User:</b>
  <%= @score.user %>
</p>


<%= link_to 'Edit', edit_level_score_path(@score.level, @score) %> |
<%= link_to 'Back', level_scores_path(@score.level) %>